Hendrik
Hevhove/webserv pull request #4
Opened 2023-01-14 19:42 UTC by Hevhove

Updated latest features with working GET and POST requests, with a basic minimal database in a json file working with php.

2023-01-15 13:55 UTC, nprimo commented on includes/utils.hpp
In this file there should be an `# include <algorithm>`

2023-01-15 13:59 UTC, nprimo commented on srcs/server/Server.cpp
line 186 - in the `catch` statement - you are missing a reference (`&`) to the `std::exception e`

2023-01-15 14:00 UTC, nprimo commented on srcs/server/Response.cpp
>  }
in line 44 - `nullptr` is a c++11 keyword apparently
![image](https://user-images.githubusercontent.com/36924670/212545159-bdcbefb6-68a8-410b-b7b1-ca03b5d8be85.png)

2023-01-15 14:38 UTC, nprimo commented on includes/GetResponse.hpp
> +/*
Why adding a new Class and not working on the existing Response Class?

2023-01-16 08:02 UTC, nprimo requested changes
To change the Makefile to avoid relinking - I left a comment in line to fix that

2023-01-16 08:02 UTC, nprimo commented on Makefile
>  OBJS			:= $(SRCS:$(SRCS_DIR)/%.cpp=$(OBJS_DIR)/%.o)
to avoid relinking here is the update line:
```
OBJS			:= $($(SRCS_DIR)/%.cpp=$(OBJS_DIR)/%.o)
```

2023-01-16 14:00 UTC, Hevhove commented on Makefile
>  OBJS			:= $(SRCS:$(SRCS_DIR)/%.cpp=$(OBJS_DIR)/%.o)
Are you sure of the above? Not working on my system for some reason. If I make any changes, webserv is always up to date and it never compiles anymore

2023-01-16 18:08 UTC, nprimo commented on Makefile
>  OBJS			:= $(SRCS:$(SRCS_DIR)/%.cpp=$(OBJS_DIR)/%.o)
You're right - the fix I suggested is breaking up the `Makefile`. The issue is linked to the rule `compile_msg` - if you remove it from the objects build up dependencies you should have a functioning `Makefile` that does not recompile

Here are the diffs to a version that does not relink
```
diff --git a/Makefile b/Makefile
index fd440fa..0529262 100644
--- a/Makefile
+++ b/Makefile
@@ -27,7 +27,8 @@ else
 endif
  
 # RULES
-$(OBJS_DIR)/%.o: $(SRCS_DIR)/%.cpp compile_msg
+$(OBJS_DIR)/%.o: $(SRCS_DIR)/%.cpp 
+       @printf "[$(C_YELLOW)=====COMPILING=====$(C_END)]\n"
        @mkdir -p $(OBJS_DIR)
        @mkdir -p $(OBJS_SUB_DIR)
        $(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@
@@ -39,8 +40,6 @@ $(NAME): $(OBJS)
  
 all: $(NAME)
  
-compile_msg:
-       @printf "[$(C_YELLOW)=====COMPILING=====$(C_END)]\n"
  
 del_msg:
        @printf "[$(C_RED)======DELETING=====$(C_END)]\n"
(END)
```

2023-01-17 11:17 UTC, Hevhove commented on Makefile
>  OBJS			:= $(SRCS:$(SRCS_DIR)/%.cpp=$(OBJS_DIR)/%.o)
I see, but unfortunately we don't see the header "COMPILING" correctly anymore. Been trying different makefiles just now and nothing seems to work to display this header before giving a list of compilation commands :/

2023-01-17 11:37 UTC, nprimo commented on Makefile
>  OBJS			:= $(SRCS:$(SRCS_DIR)/%.cpp=$(OBJS_DIR)/%.o)
I am not a big fun of all this extra information to be honest :) I prefer a clean log eheh 

But I am happy that we finally manage to find the cause of the issue, I guess that's the important thing at the end of the day ;)

2023-01-22 16:02 UTC, nprimo approved these changes
LGTM!

2023-01-23 16:06 UTC, Hevhove commented
Added in most recent keep-alive branch in here.

2023-01-23 16:06 UTC, merged